version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  static-analysis:
    executor: python/default
    steps:
      - checkout
      - run:
          command: make flake8
          name: Run flake8

workflows:
  main:
    jobs:
      - static-analysis
